source ~/.config/nvim/vim-plug.vim
"source ~/.config/nvim/coc-clangd.vim
"source ~/.config/nvim/chromatica.vim
source ~/.config/nvim/runtimepath.vim
source ~/.config/nvim/nerdtree.vim
source ~/.config/nvim/editor.vim
"source ~/.config/nvim/ycm.vim
source ~/.config/nvim/visual.vim
source ~/.config/nvim/hotkeys.vim
source ~/.config/nvim/ale-settings.vim
source ~/.config/nvim/treesitter.vim
source ~/.config/nvim/lspconfig.vim
source ~/.config/nvim/cmp.vim
